#pragma once

#define TEXIMP_COMPILER_MSVC GF_COMPILER_MSVC

#ifdef _WIN32
#define TEXIMP_PLATFORM_WINDOWS
#endif

#define TEXIMP_ENABLE_BITMAP
#define TEXIMP_ENABLE_DDS
#define TEXIMP_ENABLE_EXR
#define TEXIMP_ENABLE_JPEG
#define TEXIMP_ENABLE_KTX
#define TEXIMP_ENABLE_PNG
#define TEXIMP_ENABLE_TARGA
#define TEXIMP_ENABLE_TIFF

#ifdef TEXIMP_ENABLE_BITMAP
#define TEXIMP_ENABLE_BITMAP_BACKEND_TEXIMP

#ifdef TEXIMP_PLATFORM_WINDOWS
#define TEXIMP_ENABLE_BITMAP_BACKEND_WIC
#endif

#endif // TEXIMP_ENABLE_BITMAP

#ifdef TEXIMP_ENABLE_DDS
#define TEXIMP_ENABLE_DDS_BACKEND_TEXIMP
#endif

#ifdef TEXIMP_ENABLE_EXR
#define TEXIMP_ENABLE_EXR_BACKEND_OPENEXR
#endif

#ifdef TEXIMP_ENABLE_JPEG
#define TEXIMP_ENABLE_JPEG_BACKEND_LIBJPEG_TURBO
#endif

#ifdef TEXIMP_ENABLE_KTX
#define TEXIMP_ENABLE_KTX_BACKEND_TEXIMP
#endif

#ifdef TEXIMP_ENABLE_PNG
#define TEXIMP_ENABLE_PNG_BACKEND_LIBPNG
#endif

#ifdef TEXIMP_ENABLE_TARGA
#define TEXIMP_ENABLE_TARGA_BACKEND_TEXIMP
#endif

#ifdef TEXIMP_ENABLE_TIFF
#define TEXIMP_ENABLE_TIFF_BACKEND_TIFF
#endif